"""
models/requests.py
==================
Story 2 — Pydantic Models

All request models entering the Invincible WiFi Agent.
Every external input MUST be validated through these models.
Never accept raw dicts in agent endpoints.

AI IDE NOTE:
- These are Pydantic v2 models (use model_validator, not @validator)
- device_id format: INV-WIFI-XXXXXXXXXX
- Dates are always ISO format: YYYY-MM-DD
"""

from pydantic import BaseModel, Field, field_validator
from typing import Optional, Literal
from datetime import date, datetime
import re


class DeviceAnalysisRequest(BaseModel):
    """Single-device analysis request. Primary entry point for the agent."""
    
    device_id: str = Field(
        ...,
        description="Invincible WiFi device identifier",
        examples=["INV-WIFI-1234567890"]
    )
    analysis_date: Optional[date] = Field(
        None,
        description="Date to analyze. Defaults to today (UTC)."
    )
    include_history_days: int = Field(
        7,
        ge=1,
        le=30,
        description="How many days of history to include in analysis"
    )
    customer_account_id: Optional[str] = Field(
        None,
        description="Charter customer account ID, if known"
    )

    @field_validator("device_id")
    @classmethod
    def validate_device_id(cls, v: str) -> str:
        # Invincible WiFi devices follow INV-WIFI-XXXXXXXXXX format
        pattern = r'^INV-WIFI-\d{10}$'
        if not re.match(pattern, v):
            raise ValueError(
                f"device_id must match pattern INV-WIFI-XXXXXXXXXX. Got: {v}"
            )
        return v


class BulkDeviceRequest(BaseModel):
    """Multi-device analysis. Used for regional sweeps or bulk alerts."""
    
    device_ids: list[str] = Field(
        ...,
        min_length=1,
        max_length=100,
        description="List of device IDs to analyze. Max 100 per request."
    )
    region: Optional[str] = Field(
        None,
        description="US region filter: NE, SE, MW, SW, W"
    )
    severity_filter: Optional[Literal["GREEN", "YELLOW", "RED", "ALL"]] = Field(
        "ALL",
        description="Only return devices at or above this severity"
    )
    analysis_date: Optional[date] = None


class A2ATaskRequest(BaseModel):
    """
    A2A protocol task request from Paul Edworth (master orchestrator).
    Paul sends this format when calling our agent via A2A.
    
    DO NOT change the field names — they must match the A2A spec.
    """
    
    id: str = Field(..., description="Unique task ID generated by Paul")
    sessionId: Optional[str] = Field(None, description="Session ID for context continuity")
    message: dict = Field(
        ...,
        description="The message content from Paul. Contains 'parts' with text or data."
    )

    def get_text_input(self) -> str:
        """Extract plain text from A2A message format."""
        parts = self.message.get("parts", [])
        text_parts = [p.get("text", "") for p in parts if p.get("type") == "text"]
        return " ".join(text_parts)
